name: the_edge
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  firebase_core: ^2.28.0
  firebase_auth: ^4.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  assets:
   - assets/img1open.png
   - assets/image1.png
   - assets/image2.png
   - assets/imgdone.png
   - assets/back1.png
   - assets/back2.png
   - assets/google_logo.png
   - assets/facebook_logo.png

  
  uses-material-design: true

  