// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0Bd9evtefMkpliNMhsuIvFILczFB7Hys',
    appId: '1:437804270865:web:6a75885ba847084296f8b0',
    messagingSenderId: '437804270865',
    projectId: 'the-edge-17031',
    authDomain: 'the-edge-17031.firebaseapp.com',
    storageBucket: 'the-edge-17031.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCq994B2ngkIztR1OJov_jvTcHOHqbZfnc',
    appId: '1:437804270865:android:8418388512c077f796f8b0',
    messagingSenderId: '437804270865',
    projectId: 'the-edge-17031',
    storageBucket: 'the-edge-17031.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIM2gNiU6ygSYgUj0rkA1er3RT0OqJF3Q',
    appId: '1:437804270865:ios:fb19110195c6f71b96f8b0',
    messagingSenderId: '437804270865',
    projectId: 'the-edge-17031',
    storageBucket: 'the-edge-17031.appspot.com',
    iosBundleId: 'com.example.theEdge',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIM2gNiU6ygSYgUj0rkA1er3RT0OqJF3Q',
    appId: '1:437804270865:ios:2d77b662b2066ddd96f8b0',
    messagingSenderId: '437804270865',
    projectId: 'the-edge-17031',
    storageBucket: 'the-edge-17031.appspot.com',
    iosBundleId: 'com.example.theEdge.RunnerTests',
  );
}
